# Generated by Django 3.1.3 on 2020-11-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='description', max_length=140),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default='ingredients', max_length=140),
        ),
        migrations.AddField(
            model_name='post',
            name='method',
            field=models.TextField(default='method', max_length=140),
        ),
    ]
