# Generated by Django 3.1.3 on 2020-11-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201120_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='description', max_length=140),
        ),
    ]
